# Generated by Django 4.2.7 on 2023-11-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default='default_image.jpg', upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='language',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
