# Generated by Django 5.0.3 on 2024-04-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevels',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
