# Generated by Django 5.0.3 on 2024-04-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="country",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="country",
        ),
        migrations.AlterField(
            model_name="studentorder",
            name="completion_status",
            field=models.CharField(
                choices=[(0, "On-going"), (1, "Completed")], default=0, max_length=10
            ),
        ),
    ]
