# Generated by Django 5.0.3 on 2024-04-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "genioapp",
            "0002_remove_student_country_remove_studentprofile_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentorder",
            name="completion_status",
            field=models.CharField(
                choices=[(0, "ongoing"), (1, "completed")], default=0, max_length=10
            ),
        ),
    ]
