# Generated by Django 5.0.3 on 2024-04-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courselevels",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=25, max_digits=10, null=True
            ),
        ),
    ]
