# Generated by Django 4.2.7 on 2023-11-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genioapp', '0002_alter_instructorprofile_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genioapp.courselevels')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genioapp.studentprofile')),
            ],
        ),
    ]
