# Generated by Django 5.0.3 on 2024-04-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0003_courselevels_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentorder",
            name="payment_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
