# Generated by Django 5.0.3 on 2024-04-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0003_alter_studentorder_completion_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentorder",
            name="completion_status",
            field=models.CharField(
                choices=[(0, "On-going"), (1, "Completed")], default=0, max_length=10
            ),
        ),
    ]
