# Generated by Django 4.2.6 on 2023-11-17 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0004_rename_user_instructorprofile_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructorprofile",
            old_name="username",
            new_name="user",
        ),
    ]
