# Generated by Django 4.2.7 on 2023-11-17 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0003_remove_instructor_country"),
        ("genioapp", "0005_rename_username_instructorprofile_user"),
    ]

    operations = []
