# Generated by Django 4.2.6 on 2023-11-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0005_rename_username_instructorprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="level",
        ),
        migrations.CreateModel(
            name="CourseLevels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genioapp.course",
                    ),
                ),
            ],
        ),
    ]
