# Generated by Django 4.2.7 on 2023-11-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genioapp', '0006_merge_20231117_2225'),
        ('genioapp', '0006_remove_course_level_courselevels'),
    ]

    operations = [
    ]
