# Generated by Django 4.2.6 on 2023-11-17 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0006_remove_course_level_courselevels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.AddField(
            model_name="courselevels",
            name="students",
            field=models.ManyToManyField(blank=True, to="genioapp.student"),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_teaching",
                to="genioapp.instructorprofile",
            ),
        ),
    ]
