# Generated by Django 4.2.6 on 2023-11-20 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("genioapp", "0008_remove_course_categories_remove_course_students_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntructorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField(default=0)),
                ("start_time", models.TimeField(default="08:00")),
                ("end_time", models.TimeField(default="09:00")),
                ("available", models.BooleanField(default=False)),
                (
                    "instructor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genioapp.instructorprofile",
                    ),
                ),
            ],
        ),
    ]
