# Generated by Django 4.2.6 on 2023-11-21 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("genioapp", "0009_intructoravailability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intructoravailability",
            name="day",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
