# Generated by Django 4.2.6 on 2023-11-21 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("genioapp", "0010_remove_course_students_remove_instructor_students_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="status",
        ),
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
