# Generated by Django 4.2.6 on 2023-11-21 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("genioapp", "0010_remove_course_students_remove_instructor_students_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="status",
        ),
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.IntegerField(
                        choices=[
                            (1, "Session 1"),
                            (2, "Session 2"),
                            (3, "Session 3"),
                            (4, "Session 4"),
                        ]
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "course_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genioapp.courselevels",
                    ),
                ),
            ],
        ),
    ]
